In [2]:
import numpy as np
import h5py

In [3]:
h5_path = '/home/jan/Documents/CodeTDMStoHDF/Ausgangsdaten/examplerRun.h5'
Slice_name = 'Slice00065'
part_name = '0_00003_Canti3_cls'

In [309]:
h5 = h5py.File(h5_path)                                          #with h5py.File(h5_path,'r') as h5: 

Y_Axis = np.array(h5[part_name][Slice_name]['Y-Axis'][:]).astype(int)
Area = np.array(h5[part_name][Slice_name]['Area'][:]).astype(int)
Intensity = np.array(h5[part_name][Slice_name]['Intensity'][:]).astype(int)
X_Axis = np.array(h5[part_name][Slice_name]['X-Axis'][:]).astype(int)
h5.close()

In [308]:
h5.close()

In [87]:
X_Axis

array([6039, 6039, 6039, ..., 9567, 9567, 9567])

In [88]:
Y_Axis.size

142803

In [89]:
Y_Axis

array([-19584, -19584, -19584, ..., -19584, -19584, -19584])

In [90]:
#Duplikate herausfiltern array mit allen X und Y- Kombinationen erstellen -> Duplikate herausfinden

In [91]:
xy_combos = np.stack((X_Axis, Y_Axis), axis=-1)

In [92]:
xy_combos

array([[  6039, -19584],
       [  6039, -19584],
       [  6039, -19584],
       ...,
       [  9567, -19584],
       [  9567, -19584],
       [  9567, -19584]])

In [54]:
xy_combos_unique = np.unique(xy_combos,axis=0)

In [55]:
xy_combos_unique.shape[0]

73880

In [56]:
result_area = np.where(Area== 0)

In [69]:
result_area[0].shape[0]

62264

In [58]:
result_intensity = np.where(Intensity==0)

In [68]:
result_intensity[0].shape[0]

66411

In [71]:
no_area_intensity = np.intersect1d(result_area, result_intensity)

In [93]:
index_list_Zeros = no_area_intensity#.tolist()

In [95]:
X_Axis_wo_Zeros = np.delete(X_Axis, index_list_Zeros)
Y_Axis_wo_Zeros = np.delete(Y_Axis, index_list_Zeros)
Area_wo_Zeros = np.delete(Area, index_list_Zeros)
Intensity_wo_Zeros = np.delete(Intensity, index_list_Zeros)

In [98]:
Area_wo_Zeros.shape

(81556,)

In [99]:
Intensity_wo_Zeros.shape

(81556,)

In [100]:
X_Axis_wo_Zeros.shape

(81556,)

In [101]:
Y_Axis_wo_Zeros.shape

(81556,)

In [102]:
# Zeros filtered out at this point --> remove duplicates

In [166]:
# all xy and y positions without only Zeros
xy_combos_wo_zeros_only = np.stack((X_Axis_wo_Zeros, Y_Axis_wo_Zeros), axis = -1)

In [167]:
xy_combos_wo_zeros_only_unique, unique_indexes = np.unique(xy_combos_wo_zeros_only,axis=0, return_index = True)

In [172]:
unique_indexes.shape

(64117,)

In [173]:
xy_combos_wo_zeros_only.shape

(81556, 2)

In [174]:
Index_range = np.arange(xy_combos_wo_zeros_only.shape[0])

In [303]:
indices_of_interest = np.setdiff1d(Index_range, unique_indexes)
indices_of_interest.shape

(17439,)

In [294]:
xy_combo_array = np.empty([0,2],dtype= int)
area_max_array = np.empty([0,1],dtype= int)
intensity_max_array = np.empty([0,1],dtype= int)

In [234]:
xy_combo = xy_combos_wo_zeros_only[3]

In [222]:
row_indices = np.where(xy_combos_wo_zeros_only == xy_combos_wo_zeros_only[3])[0]

In [227]:
np.amax(Area_wo_Zeros[row_indices])

366

In [257]:
xy_combo_array

array([], shape=(0, 2), dtype=int64)

In [274]:
example_array = np.asarray([1,2])
example_array

array([1, 2])

In [275]:
xy_combo

array([ 10985, -25033])

In [290]:
xy_combo_array = np.vstack((xy_combo_array, xy_combo))

In [306]:
xy_combo_array
np.hsplit(xy_combo_array, 2)

[array([[10985],
        [ 9549],
        [ 9577],
        [10947],
        [10938],
        [ 9564],
        [10972],
        [ 9567],
        [10969],
        [ 9602],
        [10953],
        [ 9555],
        [10944],
        [ 9574],
        [10909],
        [ 9552],
        [ 9571],
        [10931],
        [ 9637],
        [10922],
        [10941],
        [ 9593],
        [10906],
        [ 9624],
        [10928],
        [ 9659],
        [ 9590],
        [10979],
        [ 9608],
        [10982],
        [ 9586],
        [10950],
        [ 9612],
        [10963],
        [ 9621],
        [10916],
        [10884],
        [ 9599],
        [10966],
        [ 9643],
        [10957],
        [ 9615],
        [10925],
        [ 9646],
        [ 9652],
        [10890],
        [10862],
        [ 9630],
        [ 9558],
        [10827],
        [ 9583],
        [10913],
        [ 9561],
        [10935],
        [10881],
        [ 9580],
        [10900],
        [ 9640],
        [10805

In [295]:
for index in indices_of_interest:
    print(index)
    #check ob xy combo in array
    if xy_combos_wo_zeros_only[index] not in xy_combo_array:
    #getting the x and y value combination of that particular index
        xy_combo = xy_combos_wo_zeros_only[index]
        #alle indizes von genau dieser Kombi suchen
        indices_of_combo = np.where(xy_combos_wo_zeros_only == xy_combo)[0]
        #über indizes die werte finden + mean oder max berechnen
        area_of_combo = Area_wo_Zeros[indices_of_combo]
        intensity_of_combo = Intensity_wo_Zeros[indices_of_combo]
        max_area_of_combo = np.amax(area_of_combo)
        max_intensity_of_combo = np.amax(intensity_of_combo)
        #xy combo in array und area und intensität auch 
        xy_combo_array = np.vstack((xy_combo_array,xy_combo))
        area_max_array = np.vstack((area_max_array, max_area_of_combo))
        intensity_max_array = np.vstack((intensity_max_array, max_intensity_of_combo))
        # die zu einem großen array machen

3
187
378
379
380
381
382
383
384
385
386
387
388
389
390
578
762
770
771
772
773
774
775
776
777
778
779
780
781
969
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1177
1361
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1566
1757
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
2140
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2522
2530
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2914
3105
3113
3114
3115
3116
3117
3118
3119
3120
3121
3122
3123
3127
3318
3502
3503
3504
3505
3506
3507
3508
3509
3510
3511
3512
3513
3518
3709
3893
3894
3895
3896
3897
3898
3899
3900
3901
3902
3903
4083
4274
4282
4283
4284
4285
4286
4287
4288
4289
4290
4291
4292
4293
4481
4665
4673
4674
4675
4676
4677
4678
4679
4680
4681
4682
4683
4684
4685
4873
5064
5065
5066
5067
5068
5069
5070
5071
5072
5073
5074
5075
5111
5334
5518
5519
5520
5521
5522
5523
5524
5525
5526
5527
5528
5529
5530
5862
6197
6198
6199
6200
6201
6202
6203
6204
6205
62

31123
31133
31159
31169
31173
31180
31183
31190
31204
31209
31216
31219
31223
31226
31230
31233
31240
31245
31255
31259
31266
31269
31276
31280
31290
31316
31326
31359
31369
31373
31383
31390
31409
31416
31419
31423
31426
31430
31433
31440
31445
31455
31459
31466
31469
31476
31480
31490
31502
31509
31512
31516
31519
31526
31559
31566
31569
31583
31609
31616
31619
31623
31626
31630
31633
31640
31645
31655
31659
31666
31669
31676
31680
31690
31695
31702
31705
31709
31712
31716
31719
31726
31739
31740
31741
31742
31743
31744
31745
31746
31747
31748
31749
31750
31751
31752
31768
31778
31782
31792
31825
31832
31835
31839
31842
31849
31861
31871
31875
31882
31885
31892
31896
31906
31911
31918
31921
31925
31928
31932
31935
31942
31961
31968
31978
31982
31992
32025
32035
32042
32049
32061
32071
32075
32082
32085
32092
32096
32106
32111
32118
32121
32125
32128
32132
32135
32142
32161
32168
32171
32178
32182
32192
32225
32235
32261
32271
32275
32282
32285
32287
32288
32296
32315
32322
32332
3236

54616
54635
54642
54645
54652
54656
54666
54709
54735
54745
54749
54756
54759
54766
54780
54785
54792
54795
54799
54802
54806
54809
54816
54821
54831
54835
54842
54845
54852
54856
54866
54892
54902
54935
54945
54949
54952
54959
54966
54981
54985
54992
54995
54999
55002
55006
55016
55021
55031
55035
55038
55042
55045
55052
55056
55078
55085
55088
55092
55102
55135
55145
55149
55152
55159
55181
55185
55192
55195
55199
55202
55206
55216
55221
55231
55235
55238
55242
55243
55246
55249
55256
55260
55266
55267
55286
55300
55303
55339
55343
55350
55353
55357
55360
55379
55389
55393
55396
55400
55403
55410
55414
55425
55429
55436
55439
55443
55446
55450
55460
55479
55486
55496
55500
55539
55543
55553
55560
55579
55589
55593
55596
55600
55603
55610
55615
55625
55629
55636
55639
55646
55650
55660
55672
55679
55682
55686
55689
55696
55729
55736
55739
55753
55779
55786
55789
55793
55796
55800
55803
55810
55815
55825
55829
55836
55839
55846
55850
55860
55865
55872
55875
55879
55882
55886
55889
5589

61804
61805
61806
61807
61808
61809
61810
61811
61813
61814
61815
61816
61817
61818
61819
61820
61822
61823
61824
61825
61826
61827
61828
61829
61830
61832
61833
61834
61835
61836
61837
61838
61839
61840
61842
61843
61844
61845
61846
61847
61848
61849
61850
61852
61853
61854
61855
61856
61857
61858
61859
61860
61862
61863
61864
61865
61866
61867
61868
61869
61870
61871
61873
61874
61875
61876
61877
61878
61879
61880
61882
61883
61884
61885
61886
61887
61888
61889
61891
61892
61893
61894
61895
61896
61897
61898
61900
61901
61902
61903
61904
61905
61906
61907
61909
61910
61911
61912
61913
61914
61915
61916
61917
61919
61920
61921
61922
61923
61924
61925
61926
61927
61929
61930
61931
61932
61933
61934
61935
61936
61938
61939
61940
61941
61942
61943
61944
61945
61946
61948
61949
61950
61951
61952
61953
61954
61955
61956
61958
61959
61960
61961
61962
61963
61964
61965
61966
61968
61969
61970
61971
61972
61973
61974
61975
61976
61977
61979
61980
61981
61982
61983
61984
61985
61986
61987
6198

65324
65325
65326
65327
65328
65329
65330
65331
65332
65333
65335
65336
65337
65338
65339
65340
65341
65342
65343
65344
65345
65347
65348
65349
65350
65351
65352
65353
65354
65355
65356
65358
65359
65360
65361
65362
65363
65364
65365
65366
65367
65368
65369
65371
65372
65373
65374
65375
65376
65377
65378
65380
65381
65382
65383
65384
65385
65386
65387
65388
65390
65391
65392
65393
65394
65395
65396
65397
65398
65400
65401
65402
65403
65404
65405
65406
65407
65408
65410
65411
65412
65413
65414
65415
65416
65417
65418
65419
65421
65422
65423
65424
65425
65426
65427
65428
65429
65431
65432
65433
65434
65435
65436
65437
65438
65439
65441
65442
65443
65444
65445
65446
65447
65448
65449
65450
65452
65453
65454
65455
65456
65457
65458
65459
65460
65461
65463
65464
65465
65466
65467
65468
65469
65470
65471
65472
65475
65476
65477
65478
65479
65480
65481
65482
65483
65485
65486
65487
65488
65489
65490
65491
65492
65493
65494
65496
65497
65498
65499
65500
65501
65502
65503
65504
65506
65507
6550

68752
68753
68754
68755
68756
68757
68758
68759
68761
68762
68763
68764
68765
68766
68767
68768
68769
68770
68772
68773
68774
68775
68776
68777
68778
68779
68780
68781
68783
68784
68785
68786
68787
68788
68789
68790
68791
68792
68794
68795
68796
68797
68798
68799
68800
68801
68802
68803
68804
68806
68807
68808
68809
68810
68811
68812
68813
68814
68815
68816
68818
68819
68820
68821
68822
68823
68824
68825
68826
68827
68829
68830
68831
68832
68833
68834
68835
68836
68837
68838
68839
68841
68842
68843
68844
68845
68846
68847
68848
68849
68850
68851
68853
68854
68855
68856
68857
68858
68859
68860
68861
68862
68863
68865
68866
68867
68868
68869
68870
68871
68872
68873
68874
68876
68877
68878
68879
68880
68881
68882
68883
68884
68885
68886
68888
68889
68890
68891
68892
68893
68894
68895
68896
68897
68898
68900
68901
68902
68903
68904
68905
68906
68907
68908
68909
68910
68912
68913
68914
68915
68916
68917
68918
68919
68920
68922
68923
68924
68925
68926
68927
68928
68929
68931
68932
68933
6893

In [299]:
xy_combo_array.shape

(134, 2)

In [300]:
area_max_array.shape

(134, 1)

In [302]:
intensity_max_array.shape

(134, 1)

In [301]:
xy_combos_wo_zeros_only[unique_indexes].shape

(64117, 2)

In [171]:
xy_combos_wo_zeros_only_unique

array([[  9549, -28561],
       [  9549, -28551],
       [  9549, -28550],
       ...,
       [ 10985, -19568],
       [ 10985, -19566],
       [ 10985, -19565]])

In [126]:
xy_combos_wo_zeros_only_unique_list = xy_combos_wo_zeros_only_unique.tolist()

In [127]:
for position in xy_combos_wo_zeros_only_unique_list


[ expression for item in list if conditional ]

[[9549, -28561],
 [9549, -28551],
 [9549, -28550],
 [9549, -28547],
 [9549, -28545],
 [9549, -28543],
 [9549, -28541],
 [9549, -28538],
 [9549, -28536],
 [9549, -28534],
 [9549, -28532],
 [9549, -28529],
 [9549, -28528],
 [9549, -28525],
 [9549, -28523],
 [9549, -28520],
 [9549, -28519],
 [9549, -28517],
 [9549, -28516],
 [9549, -28514],
 [9549, -28512],
 [9549, -28510],
 [9549, -28507],
 [9549, -28505],
 [9549, -28503],
 [9549, -28501],
 [9549, -28498],
 [9549, -28497],
 [9549, -28494],
 [9549, -28492],
 [9549, -28490],
 [9549, -28488],
 [9549, -28485],
 [9549, -28483],
 [9549, -28481],
 [9549, -28479],
 [9549, -28476],
 [9549, -28475],
 [9549, -28472],
 [9549, -28470],
 [9549, -28468],
 [9549, -28466],
 [9549, -28463],
 [9549, -28461],
 [9549, -28460],
 [9549, -28459],
 [9549, -28457],
 [9549, -28454],
 [9549, -28453],
 [9549, -28450],
 [9549, -28448],
 [9549, -28446],
 [9549, -28444],
 [9549, -28441],
 [9549, -28439],
 [9549, -28438],
 [9549, -28437],
 [9549, -28435],
 [9549, -28432

In [124]:
xy_combos_checked = np.empty([2,0])

In [125]:
xy_combos_checked

array([], shape=(2, 0), dtype=float64)

In [103]:
xyai_combos_wo_zeros = np.stack((X_Axis_wo_Zeros, Y_Axis_wo_Zeros,Area_wo_Zeros, Intensity_wo_Zeros ), axis=-1)

In [104]:
xyai_combos_wo_zeros

array([[ 10985, -25017,      0,    351],
       [ 10985, -25024,     70,    444],
       [ 10985, -25033,    141,    471],
       ...,
       [  9567, -19584,    199,      0],
       [  9567, -19584,    199,      0],
       [  9567, -19584,     99,      0]])

In [112]:
np.unique(xyai_combos_wo_zeros, axis = 0, return_counts = True)

(array([[  9549, -28561,     16,      0],
        [  9549, -28561,     33,      0],
        [  9549, -28561,     41,      0],
        ...,
        [ 10985, -19565,    183,    540],
        [ 10985, -19565,    232,    588],
        [ 10985, -19565,    250,    554]]), array([1, 2, 1, ..., 1, 1, 1]))