In [2]:
import numpy as np
import h5py
import pandas as pd

In [116]:
def dimension_check(h5_path, part_name, Slice_name):
    with h5py.File(h5_path,'r') as h5:
        X_Axis = h5[part_name][Slice_name]['X-Axis']
        Y_Axis = h5[part_name][Slice_name]['Y-Axis']
        Area = h5[part_name][Slice_name]['Area']
        Intensity = h5[part_name][Slice_name]['Intensity']
        
        X_Axis_size = X_Axis.size
        Y_Axis_size = Y_Axis.size
        Area_size = Area.size
        Intensity_size = Intensity.size 
        
        #while_Schleife muss hier gleich mit rein 
        
        if not X_Axis_size == Y_Axis_size == Area_size == Intensity_size:
            
            #find out which one is the lowest value
            size_arr = np.array([X_Axis_size, Y_Axis_size, Area_size, Intensity_size])
            min_size = size_arr.min()
            
            if X_Axis_size != min_size:
                diff_size_x = X_Axis_size - min_size
                X_Axis_new = np.delete(X_Axis, -diff_size_x)
                X_Axis = X_Axis_new
                X_Axis_size = X_Axis.size
            
            if Y_Axis_size != min_size:
                diff_size_y = Y_Axis_size - min_size
                Y_Axis_new = np.delete(Y_Axis, -diff_size_y)
                Y_Axis = Y_Axis_new
                Y_Axis_size = Y_Axis.size            
            
            if Area_size != min_size:
                diff_size_area = Area_size - min_size
                Area_new = np.delete(Area, -diff_size_area)
                Area = Area_new
                Area_size = Area.size 
                
            if Intensity_size != min_size:
                diff_size_intensity = Intensity_size - min_size
                Intensity_new = np.delete(Intensity, -diff_size_intensity)
                Intensity = Intensity_new
                Intensity_size = Intensity.size 
            
            
            size_arr = np.array([X_Axis_size, Y_Axis_size, Area_size, Intensity_size])

            
            
#            size_arr = np.array([X_Axis_size, Y_Axis_size, Area_size, Intensity_size])
#            #find the minimum value and compare each size with it
#            pos_failsize_array = np.where(size_arr != size_arr.min())
#            if 0 in pos_failsize_array:
#                X_Axis_new = np.delete(X_Axis, -1)
#                X_Axis = X_Axis_new
#                X_Axis_size = X_Axis.size
#            elif 1 in pos_failsize_array:
#                Y_Axis_new = np.delete(Y_Axis, -1)
#                Y_Axis = Y_Axis_new
#                Y_Axis_size = Y_Axis.size
#            elif 2 in pos_failsize_array:
#                Area_new = np.delete(Area, -1)
#                Area = Area_new
#                Area_size = Area.size
#                print(Area.size)
#            elif 3 in pos_failsize_array:
#                Intensity_new = np.delete(Intensity, -1)
#                Intensity = Intensity_new
#                Intensity_size = Intensity.size
#            
#        size_arr = np.array([X_Axis_size, Y_Axis_size, Area_size, Intensity_size])
            
        print(size_arr)
            
#In [9]: a=np.array([5,1,2,3,10,4])

#In [10]: np.where(a == a.min())
#Out[10]: (array([1]),)

#In [11]: np.where(a == a.max())
#Out[11]: (array([4]),)
        

In [117]:
df_Slice3 = dimension_check('/home/jan/Documents/CodeTDMStoHDF/Ausgangsdaten/examplerRun.h5','0_00003_Canti3_cls','Slice00009')

[143602 143602 143602 143602]


In [26]:
def get_2D_data_from_h5(h5_path, part_name, Slice_name):
    with h5py.File(h5_path,'r') as h5:
        X_Axis = h5[part_name][Slice_name]['X-Axis']
        Y_Axis = h5[part_name][Slice_name]['Y-Axis']
        Area = h5[part_name][Slice_name]['Area']
        Intensity = h5[part_name][Slice_name]['Intensity']
        
        print((X_Axis).size)
        help_arr = np.column_stack((X_Axis, Y_Axis, Area, Intensity))
        df = pd.DataFrame(help_arr, columns=['x','y','area','intensity'])
        return df

In [41]:
df_Slice2 = get_2D_data_from_h5_with_dimension_check('/home/jan/Documents/CodeTDMStoHDF/Ausgangsdaten/examplerRun.h5','0_00003_Canti3_cls','Slice00002')
df_Slice2

x        y  area  intensity
0        7437.0 -19584.0   0.0        0.0
1        7437.0 -19584.0   0.0        0.0
2        7437.0 -19584.0   0.0        0.0
3        7437.0 -19584.0   0.0        0.0
4        7437.0 -19584.0   0.0        0.0
...         ...      ...   ...        ...
143597  10965.0 -19584.0   0.0        0.0
143598  10965.0 -19584.0   0.0        0.0
143599  10965.0 -19584.0   0.0        0.0
143600  10965.0 -19584.0   0.0        0.0
143601  10965.0 -19584.0   0.0        0.0

[143602 rows x 4 columns]

In [48]:
df_Slice3 = get_2D_data_from_h5_with_dimension_check('/home/jan/Documents/CodeTDMStoHDF/Ausgangsdaten/examplerRun.h5','0_00003_Canti3_cls','Slice00003')
df_Slice3

x        y  area  intensity
0       6039.0 -19584.0   0.0        0.0
1       6039.0 -19584.0   0.0        0.0
2       6039.0 -19584.0   0.0        0.0
3       6039.0 -19584.0   0.0        0.0
4       6039.0 -19584.0   0.0        0.0
...        ...      ...   ...        ...
143197  9567.0 -19584.0   0.0        0.0
143198  9567.0 -19584.0   0.0        0.0
143199  9567.0 -19584.0   0.0        0.0
143200  9567.0 -19584.0   0.0        0.0
143201  9567.0 -19584.0   0.0        0.0

[143202 rows x 4 columns]

In [ ]:
df_Slice8 = get_2D_data_from_h5_with_dimension_check('/home/jan/Documents/CodeTDMStoHDF/Ausgangsdaten/examplerRun.h5','0_00003_Canti3_cls','Slice00009')
df_Slice8

In [ ]:
def get_2D_data_from_h5_with_dimension_check(h5_path, part_name, Slice_name):
    with h5py.File(h5_path,'r') as h5:
        X_Axis = h5[part_name][Slice_name]['X-Axis']
        Y_Axis = h5[part_name][Slice_name]['Y-Axis']
        Area = h5[part_name][Slice_name]['Area']
        Intensity = h5[part_name][Slice_name]['Intensity']
        
        X_Axis_size = X_Axis.size
        Y_Axis_size = Y_Axis.size
        Area_size = Area.size
        Intensity_size = Intensity.size 
             
        while not X_Axis_size == Y_Axis_size == Area_size == Intensity_size:
            
        M
                
            
            #size_arr = np.array([X_Axis_size, Y_Axis_size, Area_size, Intensity_size])

            #pos_failsize_array = np.where(size_arr != size_arr.min())
           
        #by reducing all the dimensions to the minimum equal dimensions are guaranteed 
        #there is a risk of deleting more than just one datapoint without noticing -> maybe add an alert after more than 5(?) while iterations
        help_arr = np.column_stack((X_Axis, Y_Axis, Area, Intensity))
        df = pd.DataFrame(help_arr, columns=['x','y','area','intensity'])
        return df    

In [78]:
play_arr = np.array([0, 1, 3])

In [112]:
play_arr.min()

0

In [79]:
if 0 in play_arr:
    print('0 is in play_arr')              
elif 1 in play_arr:
    print('1 is in play_arr') 
elif 2 in play_arr:
    print('2 is in play_arr') 
elif 3 in play_arr:
    print('3 is in play_arr') 

0 is in play_arr


In [80]:
0 in play_arr

True

In [81]:
1 in play_arr

True

In [82]:
2 in play_arr

False

In [83]:
3 in play_arr

True

In [94]:
np.any(play_arr == 2)

False